// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSExtensionManager.Models;

namespace server.Migrations
{
    [DbContext(typeof(VSExtensionManagerContext))]
    [Migration("20180817152634_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VSExtensionManager.Models.Extension", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ExtensionListId");

                    b.Property<string>("Name");

                    b.Property<string>("VsixId");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionListId");

                    b.ToTable("Extension");
                });

            modelBuilder.Entity("VSExtensionManager.Models.ExtensionList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("PackageIdentifier");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("ExtensionList");
                });

            modelBuilder.Entity("VSExtensionManager.Models.Gallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName");

                    b.HasKey("Id");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("VSExtensionManager.Models.Package", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<DateTime>("DatePublished");

                    b.Property<string>("Description");

                    b.Property<long?>("ExtensionListId");

                    b.Property<string>("FileName");

                    b.Property<long>("GalleryId");

                    b.Property<string>("GettingStartedUrl");

                    b.Property<string>("Icon");

                    b.Property<bool>("Included");

                    b.Property<string>("IssueTracker");

                    b.Property<string>("License");

                    b.Property<string>("MoreInfoUrl");

                    b.Property<string>("Name");

                    b.Property<string>("PackageIdentifier");

                    b.Property<string>("Preview");

                    b.Property<string>("ReleaseNotesUrl");

                    b.Property<string>("Repo");

                    b.Property<string>("Tags");

                    b.Property<string>("Version");

                    b.Property<string>("_supportedVersionsString")
                        .HasColumnName("SupportedVersions");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionListId");

                    b.HasIndex("GalleryId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("VSExtensionManager.Models.Extension", b =>
                {
                    b.HasOne("VSExtensionManager.Models.ExtensionList")
                        .WithMany("Extensions")
                        .HasForeignKey("ExtensionListId");
                });

            modelBuilder.Entity("VSExtensionManager.Models.Package", b =>
                {
                    b.HasOne("VSExtensionManager.Models.ExtensionList", "ExtensionList")
                        .WithMany()
                        .HasForeignKey("ExtensionListId");

                    b.HasOne("VSExtensionManager.Models.Gallery", "Gallery")
                        .WithMany("Packages")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
